#!/usr/bin/env python3
"""Generate the static (GitHub Pages) build of the annotation study.

Reuses the Flask app's config + task-assignment logic to emit two files at the
repo root:

  study.json   the study config + the assigned tasks (with per-step segment
               timings and STATIC video paths). No ground truth is ever written.
  index.html   a copy of annotation_app/static/index.html rewired to load the
               static bundle (study.json + backend.js) instead of the /api/*
               server. Videos, CSS and JS are referenced by repo-relative paths
               so GitHub Pages can serve everything from the repo root.

Run it whenever config.py, the task selection, or the frontend HTML changes:

    cd annotation_app
    python3 build_static.py
"""
from __future__ import annotations

import copy
import json
import os

import app  # noqa: E402  (imports config, builds MANIFEST)
import config  # noqa: E402

REPO_ROOT = config.REPO_ROOT
BUNDLE_NAME = os.path.basename(config.BUNDLE_DIR.rstrip("/"))
STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")


def _staticize(task: dict, *, is_practice: bool = False) -> dict:
    task = copy.deepcopy(task)
    task["video_url"] = f"{BUNDLE_NAME}/{task['path']}/recording.mp4"
    if is_practice:
        task["is_practice"] = True
    for step in task.get("steps", []):
        step.pop("gt", None)  # never publish answers in the static bundle
    return task


def build_tasks() -> list[dict]:
    """Assigned study tasks with STATIC video paths and no ground-truth leakage."""
    return [_staticize(app.MANIFEST_BY_ID[tid]) for tid in app._assign_tasks()
            if tid in app.MANIFEST_BY_ID]


def build_practice_tasks() -> list[dict]:
    return [_staticize(t, is_practice=True) for t in app._practice_tasks()]


def build_study_json() -> dict:
    return {
        "config": app._study_config(),
        "completion_url": config.PROLIFIC_COMPLETION_URL or None,
        "completion_code": config.COMPLETION_CODE,
        "tasks": build_tasks(),
        "practice_tasks": build_practice_tasks(),
    }


def build_index_html() -> str:
    with open(os.path.join(STATIC_DIR, "index.html"), encoding="utf-8") as f:
        html = f.read()

    html = html.replace('href="/static/', 'href="annotation_app/static/')
    bootstrap = (
        '<script>window.STUDY_STATIC=true;window.STUDY_URL="study.json";</script>\n'
        '  <script src="annotation_app/static/backend.js"></script>\n'
        '  <script src="annotation_app/static/app.js"></script>'
    )
    html = html.replace('<script src="/static/app.js"></script>', bootstrap)
    banner = ("<!-- AUTO-GENERATED by annotation_app/build_static.py — do not edit "
              "by hand. Edit annotation_app/static/index.html and rebuild. -->\n")
    return banner + html


def main() -> None:
    study = build_study_json()
    with open(os.path.join(REPO_ROOT, "study.json"), "w", encoding="utf-8") as f:
        json.dump(study, f, ensure_ascii=False, indent=2)

    with open(os.path.join(REPO_ROOT, "index.html"), "w", encoding="utf-8") as f:
        f.write(build_index_html())

    n_steps = sum(len(t["steps"]) for t in study["tasks"])
    n_prac = len(study.get("practice_tasks") or [])
    print(f"Wrote study.json ({len(study['tasks'])} tasks, {n_steps} steps, "
          f"{n_prac} practice) and index.html to {REPO_ROOT}")
    if study["config"].get("dev_mode"):
        print("WARNING: DEV_MODE is True — but ground truth is stripped from "
              "study.json anyway. Set DEV_MODE=False for the real study.")


if __name__ == "__main__":
    main()
