#!/usr/bin/env python3
"""Generate the static (GitHub Pages) build for the dual multi-model study.

Emits at the repo root (9 cells = 3 bundles × screen|log|both):

  study_b1_screen.json … study_b3_both.json
  index.html   (loads study_b{N}_{evidence}.json from ?bundle=&condition=)

Stimuli: final_final_8tasks_gpt55_minimax_fable (+ MiniMax practice clip).

Run:

    cd annotation_app_dual
    python3 build_static.py
"""
from __future__ import annotations

import copy
import json
import os
from urllib.parse import quote, unquote

import app
import config
import study_mode

REPO_ROOT = config.REPO_ROOT
STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")
OUT_PREFIX = "study_b"


def _to_static_video_url(task: dict) -> str:
    """Relative path from repo root so Pages can serve the mp4."""
    url = task.get("video_url") or ""
    if url.startswith("/media/"):
        # /media/<percent-encoded segments>
        rel = "/".join(unquote(p) for p in url[len("/media/"):].split("/") if p)
        return "/".join(quote(p, safe="") for p in rel.split("/") if p)

    rec = (task.get("recording_relpath") or "").replace("\\", "/")
    if rec:
        return "/".join(quote(p, safe="") for p in rec.split("/") if p)

    path = (task.get("path") or "").replace("\\", "/")
    parts = [p for p in path.split("/") if p] + ["recording.mp4"]
    return "/".join(quote(p, safe="") for p in parts)


def _staticize(task: dict, *, keep_agent_log: bool) -> dict:
    task = copy.deepcopy(task)
    task["video_url"] = _to_static_video_url(task)
    for step in task.get("steps", []):
        gt = step.get("gt")
        if not keep_agent_log:
            step.pop("gt", None)
        elif gt:
            step["gt"] = {
                "action": gt.get("action") or "",
                "response": gt.get("response") or "",
            }
    return task


def build_study_json(bundle_id: int, evidence: str) -> dict:
    evidence = study_mode.normalize_evidence(evidence)
    flags = study_mode.evidence_flags(evidence)
    keep_log = flags["show_log"]

    # Ordered tasks (default_order from manifest; client may reshuffle later).
    tasks = [
        _staticize(t, keep_agent_log=keep_log)
        for t in app.tasks_for_participant_bundle(
            bundle_id, evidence, prolific_pid="", randomize=False
        )
    ]
    practice = [
        _staticize(t, keep_agent_log=keep_log)
        for t in app.get_practice_tasks(keep_log)
    ]
    for t in practice:
        t["is_practice"] = True

    cfg = app._study_config(bundle_id=bundle_id, evidence=evidence)
    return {
        "config": cfg,
        "bundle_id": bundle_id,
        "evidence": evidence,
        "condition": evidence,
        "show_log": flags["show_log"],
        "show_video": flags["show_video"],
        "completion_url": config.PROLIFIC_COMPLETION_URL or None,
        "completion_code": config.COMPLETION_CODE,
        "tasks": tasks,
        "practice_tasks": practice,
        "study_id": study_mode.load_manifest().get("study_id"),
    }


def build_index_html() -> str:
    with open(os.path.join(STATIC_DIR, "index.html"), encoding="utf-8") as f:
        html = f.read()

    html = html.replace('href="/static/', 'href="annotation_app_dual/static/')
    bootstrap = (
        '<script>window.STUDY_STATIC=true;</script>\n'
        '  <script src="annotation_app_dual/static/backend.js"></script>\n'
        '  <script src="annotation_app_dual/static/app.js"></script>'
    )
    html = html.replace('<script src="/static/app.js"></script>', bootstrap)
    banner = (
        "<!-- AUTO-GENERATED by annotation_app_dual/build_static.py — "
        "edit annotation_app_dual/static/index.html and rebuild. -->\n"
    )
    return banner + html


def _check_videos(study: dict, label: str) -> list[str]:
    warnings = []
    for t in (study.get("tasks") or []) + (study.get("practice_tasks") or []):
        decoded = "/".join(unquote(p) for p in (t.get("video_url") or "").split("/"))
        full = os.path.join(REPO_ROOT, decoded)
        if not os.path.isfile(full):
            warnings.append(f"{label}: missing {decoded}")
    return warnings


def main() -> None:
    # Ensure manifest is current
    study_mode.load_manifest(force=True)
    written: list[str] = []
    warnings: list[str] = []

    for bid in study_mode.VALID_BUNDLES:
        for evidence in study_mode.EVIDENCE:
            study = build_study_json(bid, evidence)
            name = f"{OUT_PREFIX}{bid}_{evidence}.json"
            path = os.path.join(REPO_ROOT, name)
            with open(path, "w", encoding="utf-8") as f:
                json.dump(study, f, ensure_ascii=False, indent=2)
                f.write("\n")
            n_gt = sum(
                1 for t in study["tasks"] for s in t["steps"] if s.get("gt")
            )
            written.append(
                f"{name} ({len(study['tasks'])} tasks, "
                f"{study['config'].get('expected_tasks')} expected, "
                f"{n_gt} steps with agent log)"
            )
            warnings.extend(_check_videos(study, name))

    index_path = os.path.join(REPO_ROOT, "index.html")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(build_index_html())

    print("Wrote:")
    for line in written:
        print(f"  {line}")
    print("  index.html")
    if warnings:
        print("WARNINGS:")
        for w in warnings[:20]:
            print(f"  - {w}")
        if len(warnings) > 20:
            print(f"  … and {len(warnings) - 20} more")
    else:
        print("All video paths resolve on disk.")

    print("\nProlific / Pages links (append PROLIFIC_* params):")
    print("  …/?bundle=1&condition=screen   # Bundle A")
    print("  …/?bundle=1&condition=log")
    print("  …/?bundle=1&condition=both")
    print("  …/?bundle=2&condition=screen   # Bundle B")
    print("  …/?bundle=3&condition=screen   # Bundle C (Impress GPT-5.5)")


if __name__ == "__main__":
    main()
